apiVersion: v1
# 자원의 종류를 명시
kind: Pod
metadata:
  name: nginx-pod
  namespace: dding
  # labels는 service 의 라우팅 대상이 되는 이름
  # service 의 selector.app 을 통해서 매핑
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80