apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dding
spec:
  # node을 통해서 직접 접근 가능한 타입
  type: NodePort
  ports:
  # service의 port
  - port: 80
    # service가 라우팅 해줄 대상의 port = pod
    targetPort: 80
    nodePort: 31116
  # 어떤 파드랑 매핑 ㄱ? -> nginx_pod 의 labels.app 이랑 일치해야함(!!!)  
  selector:
    app: my-nginx 