apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  namespace: natural
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: natural
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: natural
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31116
  selector:
    app: my-nginx